background = bg_world1
background2 = bg_pixel
background3 = bg_pixel
background_xscroll = 0
background_yscroll = 0
background_xscrolloffset = 0
background_yscrolloffset = 0
background_xscroll2 = 0
background_yscroll2 = 0
background_xoffset1 = 0
background_yoffset1 = 0
background_xoffset2 = 0
background_yoffset2 = 0
foreground1_x = 0
foreground1_y = 0
foreground2_x = 0
foreground2_y = 0
backgrounds = ["Backgrounds_still1", "Backgrounds_still2", "Backgrounds_still3"]
