var _cam_x = camera_get_view_x(view_camera[0])
var _cam_y = camera_get_view_y(view_camera[0])
layer_x("Assets_background", (_cam_x * 0.2))
layer_y("Assets_background", (_cam_y * 0.2))
layer_x("Assets_background2", (_cam_x * 0.4))
layer_y("Assets_background2", (_cam_y * 0.4))
layer_x("Backgrounds_1", (background_xoffset1 + (_cam_x * 0.18)))
layer_y("Backgrounds_1", (background_yoffset1 + (_cam_y * 0.18)))
layer_x("Backgrounds_2", (background_xoffset2 + (_cam_x * 0.19)))
layer_y("Backgrounds_2", (background_yoffset2 + (_cam_y * 0.19)))
layer_x("Backgrounds_3", (_cam_x * 0.2))
layer_y("Backgrounds_3", (_cam_y * 0.2))
layer_x("Backgrounds_G1", (_cam_x * 0.2))
layer_x("Backgrounds_G2", (_cam_x * 0.18))
layer_x("Backgrounds_G3", (_cam_x * 0.16))
layer_x("Backgrounds_H1", (_cam_x * 0.11))
layer_y("Backgrounds_H1", _cam_y)
layer_x("Backgrounds_Skybox", (_cam_x * 0.25))
layer_y("Backgrounds_Skybox", (_cam_y * 0.25))
layer_x("Backgrounds_Skybox2", _cam_x)
layer_y("Backgrounds_Skybox2", _cam_y)