var _cam_x = camera_get_view_x(view_camera[0])
var _cam_y = camera_get_view_y(view_camera[0])
layer_x("Assets_background", (_cam_x * 0.2))
layer_y("Assets_background", (_cam_y * 0.2))
layer_x("Assets_background2", (_cam_x * 0.3))
layer_y("Assets_background2", (_cam_y * 0.3))
layer_x("Backgrounds_1", (background_xoffset1 + (_cam_x * 0.18)))
layer_y("Backgrounds_1", (background_yoffset1 + (_cam_y * 0.18)))
layer_x("Backgrounds_2", (background_xoffset2 + (_cam_x * 0.19)))
layer_y("Backgrounds_2", (background_yoffset2 + (_cam_y * 0.19)))
layer_x("Backgrounds_3", (_cam_x * 0.2))
layer_y("Backgrounds_3", (_cam_y * 0.2))
layer_x("Backgrounds_G1", (_cam_x * 0.2))
layer_x("Backgrounds_G2", (_cam_x * 0.18))
layer_x("Backgrounds_G3", (_cam_x * 0.16))
layer_x("Backgrounds_H1", (_cam_x * 0.11))
layer_y("Backgrounds_H1", _cam_y)
layer_x("Backgrounds_Skybox", (_cam_x * 0.25))
layer_y("Backgrounds_Skybox", (_cam_y * 0.25))
layer_x("Backgrounds_Skybox2", _cam_x)
layer_y("Backgrounds_Skybox2", _cam_y)
layer_x("Backgrounds_still1", ((stillbackground1xoffset + _cam_x) - clamp((_cam_x * (0.15 * (960 / room_width))), 0, (sprite_get_width(background_layer_sprite_get("Backgrounds_still1")) - 960))))
layer_y("Backgrounds_still1", ((stillbackground1yoffset + _cam_y) - clamp((_cam_y * (0.15 * (540 / room_height))), 0, (sprite_get_height(background_layer_sprite_get("Backgrounds_still1")) - 540))))
layer_x("Backgrounds_still2", ((stillbackground2xoffset + _cam_x) - clamp((_cam_x * (0.25 * (960 / room_width))), 0, (sprite_get_width(background_layer_sprite_get("Backgrounds_still1")) - 960))))
layer_y("Backgrounds_still2", ((stillbackground2yoffset + _cam_y) - clamp((_cam_y * (0.25 * (540 / room_height))), 0, (sprite_get_height(background_layer_sprite_get("Backgrounds_still1")) - 540))))
layer_x("Backgrounds_scrollingstill", (((background_still1xoffset + background_xscroll) + _cam_x) - clamp((_cam_x * (0.15 * (960 / room_width))), 0, (sprite_get_width(background_layer_sprite_get("Backgrounds_scrollstill")) - 960))))
layer_y("Backgrounds_scrollingstill", (((background_still1yoffset + background_yscroll) + _cam_y) - clamp((_cam_y * (0.15 * (540 / room_height))), 0, (sprite_get_height(background_layer_sprite_get("Backgrounds_scrollstill")) - 540))))
layer_x("Backgrounds_H1still", (stillbackgroundH1xoffset + (_cam_x * 0.25)))
layer_y("Backgrounds_H1still", (stillbackgroundH1yoffset + (_cam_y - clamp((_cam_y * (0.15 * (540 / room_height))), 0, (sprite_get_height(background_layer_sprite_get("Backgrounds_H1still")) - 540)))))
layer_x("Backgrounds_H2still", (stillbackgroundH2xoffset + (_cam_x * 0.25)))
layer_y("Backgrounds_H2still", (stillbackgroundH2yoffset + (_cam_y - clamp((_cam_y * (0.15 * (540 / room_height))), 0, (sprite_get_height(background_layer_sprite_get("Backgrounds_H2still")) - 540)))))
layer_x("Backgrounds_scrolling", (((_cam_x * 0.25) + background_xscroll) + background_xscrolloffset))
layer_y("Backgrounds_scrolling", (((_cam_y * 0.25) + background_yscroll) + background_yscrolloffset))
layer_x("Backgrounds_scrolling2", (((_cam_x * 0.26) + background_xscroll2) + background_xscrolloffset2))
layer_y("Backgrounds_scrolling2", (((_cam_y * 0.26) + background_yscroll2) + background_yscrolloffset2))
background_xscroll += layer_get_hspeed("Backgrounds_scrolling")
background_yscroll += layer_get_vspeed("Backgrounds_scrolling")
background_xscroll += layer_get_hspeed("Backgrounds_scrollstill")
background_yscroll += layer_get_vspeed("Backgrounds_scrollstill")
layer_x("Backgrounds_scrolling2", (((_cam_x * 0.25) + background_xscroll2) + background_xscrolloffset))
layer_y("Backgrounds_scrolling2", (((_cam_y * 0.25) + background_yscroll2) + background_yscrolloffset))
background_xscroll2 += layer_get_hspeed("Backgrounds_scrolling2")
background_yscroll2 += layer_get_vspeed("Backgrounds_scrolling2")
layer_x("Foreground_1", (_cam_x * 0.35))
layer_y("Foreground_1", (_cam_y * 0.35))
layer_x("Foreground_Ground1", (_cam_x * 0.15))
layer_y("Foreground_Ground1", (room_height - sprite_get_height(background_layer_sprite_get("Foreground_Ground1"))))
